apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verus-dev-auth-dev
  namespace: verus-dev
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: verus-group
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:010438496771:certificate/006be357-3a85-4593-b2a8-d75e65a81922
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
spec:
  ingressClassName: alb
  rules:
    - host: verus-dev.districtcyber.io
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: verus-dev-auth-dev
                port:
                  number: 80
