apiVersion: v1
kind: Service
metadata:
  name: flux-nginx
  labels:
    app: flux-nginx
spec:
  selector:
    app: flux-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
