apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps.yaml
  - flux-system/gotk-sync.yaml
patches:
  - target:
      kind: HelmRelease
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/values/ingress/annotations/alb.ingress.kubernetes.io~1certificate-arn
        value: arn:aws:acm:us-west-2:010438496771:certificate/81d69f9e-f175-4714-bcda-210e8792656e
