apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository-dev.yaml
  - gitrepository-stg.yaml
  - imagerepository.yaml
  - imagepolicy-dev.yaml
  - imagepolicy-stg.yaml
  - helmrelease-dev.yaml
  - helmrelease-stg.yaml
  - imageupdateautomation.yaml
