apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository-dev.yaml
  - gitrepository-prod.yaml
  - imagerepository.yaml
  - imagepolicy-dev.yaml
  - imagepolicy-prod.yaml
  - helmrelease-dev.yaml
  - helmrelease-prod.yaml
  - imageupdateautomation.yaml
